# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'CLUIKitExample' do

	pod 'MJRefresh'
    pod 'CLFoundation'
    pod 'YYModel'
    pod 'Masonry'
    
    # 高德地图
#    pod 'AMap3DMap'
    # 谷歌地图
#    pod 'GoogleMaps'

end

